### ISSUE TITLE
这个项目停止了么？

### ISSUE THREAD

**Issue by ijustlearn** [HAChina/redpoint#3]
请问这个项目停止了么，个人认为对于homeassistant推广还是很有意义的

**Comment by zhujisheng** [comment]
没有停。
配置的schema是在云端的，一直在不断添加和更新，会直接显示在浏览器中——这些工作不需要更新这个组件程序。

**Comment by ijustlearn** [comment]
谢谢，我已经加了讨论群了 (*^▽^*)
